# Generated by Django 3.2.5 on 2021-07-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("type_of_action", models.CharField(max_length=50)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
