[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories
    | \.direnv
    | \.venv
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
    ".direnv/*",
    ".venv/*",
    "manage.py",
    "actions/asgi.py",
    "actions/wsgi.py",
    "actions/logging.py",
]

[tool.coverage.report]
fail_under = 100
skip_covered = true

[tool.coverage.html]

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [".direnv", "venv", ".venv"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "actions.settings"
addopts = "--tb=native --ignore=node_modules"
