# Generated by Django 3.2.5 on 2021-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="description",
            new_name="org",
        ),
        migrations.RemoveField(
            model_name="action",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="action",
            name="type",
        ),
        migrations.AddField(
            model_name="action",
            name="about",
            field=models.CharField(default="about", max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="action",
            name="readme",
            field=models.CharField(default="readme", max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="action",
            name="repo_name",
            field=models.CharField(default="repo", max_length=200),
            preserve_default=False,
        ),
    ]
