# Generated by Django 3.2.5 on 2021-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0002_auto_20210713_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="action",
            name="readme",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="action",
            unique_together={("org", "repo_name")},
        ),
    ]
