# Generated by Django 3.2.5 on 2021-07-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_auto_20210715_1338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="readme",
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("readme", models.TextField()),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="actions.action"
                    ),
                ),
            ],
            options={
                "unique_together": {("action", "tag")},
            },
        ),
    ]
