# Generated by Django 3.2.5 on 2021-08-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0005_alter_version_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="actions.action",
            ),
        ),
    ]
