# Generated by Django 4.0.4 on 2022-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0008_rename_date_version_committed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="about",
            field=models.TextField(default=""),
        ),
    ]
