# Generated by Django 5.1.6 on 2025-02-26 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0009_alter_action_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={"ordering": ["-committed_at"]},
        ),
    ]
