# Generated by Django 5.2 on 2025-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0010_alter_version_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="contributors",
            field=models.JSONField(default=list),
        ),
    ]
