# Generated by Django 5.2 on 2025-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0011_action_contributors"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="topics",
            field=models.JSONField(default=list),
        ),
    ]
