# note: we do not run prod service with docker-compose, we use it just for
# configuring the production build
services:
  prod:
    # image name, both locally and public
    image: actions-registry
    build:
      context: ..
      # path relative to context
      dockerfile: docker/Dockerfile
      # the prod stage in the Dockerfile
      target: actions-registry-prod
      # should speed up the build in CI, where we have a cold cache
      cache_from:  # should speed up the build in CI, where we have a cold cache
        - ghcr.io/opensafely-core/base-docker
        - ghcr.io/opensafely-core/actions-registry
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # env vars supplied by just
        - BUILD_DATE
        - GITREF
    # use dockers builitin PID daemon
    init: true
    ports:
      - "8000:8000"

  node-assets:
    extends:
      service: prod
    image: actions-registry-node-assets
    build:
      # the node-builder stage in the Dockerfile
      target: node-builder
    volumes:
      - ..:/app

  # main development service
  dev:
    extends:
      service: prod
    image: actions-registry-dev
    container_name: actions-registry-dev
    build:
      # the dev stage in the Dockerfile
      target: actions-registry-dev
      # pass the uid/gid as build arg
      args:
        - USERID=${DEV_USERID:-1000}
        - GROUPID=${DEV_GROUPID:-1000}
    # paths relative to docker-compose.yaml file
    env_file:
      - ../.env
    volumes:
      - ..:/app
      # provides a persistant inspectable cache for staticfiles
      - ./staticfiles:/opt/staticfiles
    # override command
    command: python manage.py runserver 0.0.0.0:8000

  # test runner service - uses dev-image with a different entrypoint commnd
  test:
    extends:
      service: dev
    container_name: actions-registry-test
    # different default test env
    env_file:
      - ../.test.env
    # override entrypoint and command
    entrypoint: /app/docker/entrypoints/test.sh
    command: python -m pytest --cov=. --cov-report html --cov-report term-missing:skip-covered
