#!/usr/bin/env bash
# shellcheck source=../.venv/bin/activate

# Get a current virtual env or create one and return the path to it for use in other scripts
VIRTUAL_ENV="venv"

set -euo pipefail

# Find the project root directory
PYTHON_VERSION="${PYTHON_VERSION:-python3.9}"
BASE_DIR="$(git rev-parse --show-toplevel)"


dev_setup () {
  echo "Ensuring dev setup"

  # Ensure pip-tools has been installed
  if [[ ! -f "$VIRTUAL_ENV/bin/pip-compile" ]]; then
    echo "Installing pip tools"
    pip install pip-tools
  fi

  # Ensure dev requirements have been installed; black should be a requirement of every project, so if it isn't present
  # yet, assure we need to install them all
  if [[ ! -f "$VIRTUAL_ENV/bin/black" ]]; then
    echo "Installing dev requirements"
    pip install --require-hashes -r requirements.dev.txt
  fi

  # Ensure pre-commit has been set up
  if [[ ! -f "$BASE_DIR/.git/hooks/pre-commit" ]]; then
    echo "Setting up pre-commit hooks"
    pre-commit install
  fi

  export PYTHONPATH=$BASE_DIR
}
